# Generated by Django 4.1 on 2022-12-16 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "create_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 12, 16, 2, 42, 6, 238988, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="featured_images/% Y/% m/% d/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=36)),
                ("text", models.TextField()),
                (
                    "create_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 12, 16, 2, 42, 6, 239488, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("approved_comment", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.articlepost",
                    ),
                ),
            ],
        ),
    ]
