# Generated by Django 4.1 on 2022-12-18 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_articlepost_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
