# Generated by Django 4.1 on 2023-04-04 08:51

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("articles", "0003_alter_articlepost_create_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="featured_image",
            field=models.ImageField(blank=True, upload_to="featured_images/%Y/%m/"),
        ),
    ]
