# Generated by Django 4.1 on 2022-12-16 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 16, 2, 42, 31, 774241, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 16, 2, 42, 31, 774750, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
